### ISSUE TITLE
should we use a tandem "marker entry" in options?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#262] opened 2016-08-23 16:02 UTC
Noted in https://github.com/phetsims/scenery-phet/issues/259#issuecomment-241782395

I had some confusion about whether ArrowButton was instrumented, and said:

> No tandem appears in the ArrowButton source code, but it is passed through to its supertype (RectangularPushButton), where it appears to be handled properly.

Looking at ResetAllButton (a subtype of RoundPushButton), I see:

``` js
tandem: null // Marker entry to indicate that tandem is supported (in the parent)
```

Should ArrowButton have a similar "marker entry" in its options? Is this a convention that we're going to use?

**Comment by pixelzoom** [comment] 2016-08-23 16:03
In https://github.com/phetsims/scenery-phet/issues/259#issuecomment-241783144, @samreid said:
> I have mixed feelings about the marker and would like to discuss it before we decide. I suppose at the moment I'm leaning toward "delete them because they are duplicated information and it would be crazy to have marker entries for everything" though I do see the advantage of being able to easily see if something is instrumented in a parent class. Perhaps there is a better way to proceed.

**Comment by pixelzoom** [comment] 2016-08-23 16:03
Labeled for discussion at developer meeting.

**Comment by samreid** [comment] 2016-08-25 19:03
@jbphet points out this is just a holdover until `tandem` is supported broadly.

We would rather not duplicate options, and we should remove the marker entries.

**Comment by samreid** [comment] 2016-08-25 19:04
Marked with high-priority to put it on my todo list.

**Comment by samreid** [comment] 2016-08-29 03:20
If we decide to proceed with non-null tandems in common code options as discussed in  https://github.com/phetsims/phet-io/issues/562 then perhaps it makes sense to declare `tandem: Tandem.createOptionalTandem('myClass`)` at each point in the hierarchy--the subclassiest one will take effect.  Should be discussed with @andrewadare before proceeding.

**Comment by samreid** [comment] 2016-08-30 17:49
@andrewadare the pattern that we discussed today sounds good, and in a subclass hierarchy, each class will specify `tandem: Tandem.createDefaultTandem('myClass')`.  This is in effect like a "marker entry" but one that will work well with our non-null tandem pattern.  I'll unassign but leave open and we can re-evaluate after https://github.com/phetsims/phet-io/issues/562 is complete.

**Comment by pixelzoom** [comment] 2016-11-16 00:02
@samreid @andrewadare Is this issue still relevant?

**Comment by andrewadare** [comment] 2016-11-16 00:13
Yes, thanks for the reminder. In fact it is more relevant now that phetsims/phet-io#562 is done. I will flag for discussion with other PhET-iO devs.

**Comment by andrewadare** [comment] 2016-11-16 18:39
Noting here for future reference: FaucetNode.js in scenery-phet is a nice example to follow. It includes the createDefaultTandem call, good comments, and disposal code.

**Comment by samreid** [comment] 2016-11-21 17:35
The pattern in ArrowNode is a good pattern, with the caveat that TArrowNode should be used instead of TNode.

There are 13 `tandem: null` in sun and 9 in scenery-phet.  43 across all of our repos (including sun and scenery-phet).

To do this right, we should:
- [ ] replace `tandem: null` with `tandem: tandem.createDefaultTandem('myType')`
- [ ] make sure all sites have `tandem.addInstance()`
- [ ] make sure all sites have `tandem.removeInstance()` implemented in a private `disposeMyType` function, which is called from the public `dispose` function.
- [ ] add `Tandem.validationOptions(options)`

Before tackling this, we should:
- [ ] augment automated testing so it will test phet-io versions so we can see where tandems are missing

The latter checkbox needs a separate issue.

**Comment by samreid** [comment] 2016-11-21 17:36
On hold until #158 is complete.

**Comment by samreid** [comment] 2016-12-11 20:30
In the preceding commit, I applied the default tandem pattern to ObservableArray.  That is:

* import Tandem
* supply Tandem.createDefaultTandem('lowerCamelCaseName') in the options extend
* validate options
* remove logic that checked for existence of options or options.tandem (since we know it will always exist)

@zepumph can you please review this commit and let me know if you have any recommendations?  If all seems well, can you please apply this strategy to the remaining 39 occurrences of `tandem: null` across our codebases?

**Comment by samreid** [comment] 2016-12-16 16:28
Based on my experience in updating ObservableArray to use this pattern, we may need to make adjustments.  For instance, there were places where making ObservableArray tandemization required caused issues.  We may need to adopt another pattern for model components.

But I think this pattern could safely be applied in sun and scenery-phet.  Could you start there and let's re-evaluate before expanding scope?

**Comment by zepumph** [comment] 2017-01-02 20:03
I added defaultTandem to sun, and then went in and fixed everything I could in the sim code. @samreid can we talk at some point about a few of the ones I left. There are three errors right now, but they all seem like they will be fixed pretty quickly.

**Comment by samreid** [comment] 2017-01-02 21:23
I fixed Balloons and Static Electricity in the preceding commit.

**Comment by samreid** [comment] 2017-01-03 03:52
After the above commits, phet-io tests are green again:

![image](https://cloud.githubusercontent.com/assets/679486/21599650/6089a804-d12d-11e6-88ec-914df97a4f95.png)

**Comment by samreid** [comment] 2017-01-03 04:02
I reviewed the changes in https://github.com/phetsims/sun/commit/316617a92d110f11a4a2e28555bdc80b7b2e796c and the changes seem good.  Nice work @zepumph.  I'll leave this issue open in case there are more changes to be made.

**Comment by samreid** [comment] 2017-01-03 04:04
I am seeing issues in the non-phet-io sims though:

![image](https://cloud.githubusercontent.com/assets/679486/21599755/fdb674da-d12e-11e6-9873-fc7f875f7c8d.png)

Looking into it.

**Comment by samreid** [comment] 2017-01-03 04:17
The problem is that scenery-phet and other libraries are still using `tandem: null`, so when subclassing a sun component, the tandem is passed in as null, but sun expects it to be non-null.

**Comment by samreid** [comment] 2017-01-03 04:34
After the above commits, aqua requirejs tests are passing again for PhET brand.

**Comment by zepumph** [comment] 2017-01-03 17:00
I updated all tandem: nulls in scenery-phet

**Comment by pixelzoom** [comment] 2017-04-27 03:29
@samreid @zepumph What is the status of this issue? Is there more work to be done here? Something to review? Ready to close?

**Comment by zepumph** [comment] 2017-05-08 22:32
Thanks @pixelzoom for bring it back up.

**Comment by zepumph** [comment] 2017-05-12 20:52
I got rid of the last two spots that had "tandem:null" (Property and ObservableArray) in the project. This helped to catch a bug in MAL as well, where tandems weren't being passed into Photon. 


Here are the related commits,

tandemOptional in Property.js, factor Optional/RequiredAndNotSupplied into required and supplied options
https://github.com/phetsims/tandem/commit/294a42debbba0395d0eae356686bf01d67d84aca

instrument MAL after observableArray update
https://github.com/phetsims/molecules-and-light/commit/89857f6e4433c5a2ef273b3fddce80222fe3f1b9

tandemOptional in Property.js
https://github.com/phetsims/axon/commit/3471b0812792426bf58bd9bab8b7e0ee6d103a7b

tandemOptional in ObservableArray.js
https://github.com/phetsims/axon/commit/2a218045fb542b4ded5e847241891baff093182d


@samreid would you please look over these commits and make suggestions. I think this is probably ready to close after review.

**Comment by zepumph** [comment] 2017-06-16 20:49
@samreid here I think a review just needs to look at the above commits for fowl play. Check to make sure that tandem: null was replaced correctly.

**Comment by samreid** [comment] 2017-08-03 00:56
The preceding commits look great, thanks!  Closing.

**Closed by samreid** 2017-08-03 00:56 UTC
Labels: dev:phet-io, status:ready-for-review
