### ISSUE TITLE
NumberControl Layout

### ISSUE THREAD

**Issue by veillette** [phetsims/scenery-phet#244] opened 2016-07-06 18:38 UTC
There is a rather common pattern in our sims for slider with a numerical readout. A very common layout is to have a title at the top, then a readout with control arrows underneath and the slider at the bottom. There are several simulations that have this layout.

- Gravity Force Lab
- Plinko Probability
- Pendulum Lab
- Wave on a sttring
- Fluid Pressure and Flow
- Under Pressure
- Rutherford Scattering

(there might be others)

Right now, we have NumberControl in scenery-phet, but it does not accommodate the current layout. FYI, NumberControl is currently used in two sims (circuit-construction and Hooke's laws

Should we attempt to have another scenery-phet component, or should we try to generalize NumberControl.
 

Wave on a string
![image](https://cloud.githubusercontent.com/assets/7633344/16627708/796cfe96-437c-11e6-8712-e0681c774e79.png)

Fluid Pressure and Flow
![image](https://cloud.githubusercontent.com/assets/7633344/16627722/8d36440a-437c-11e6-852e-32359e0fcfb2.png)
Rutherfors Scattering
![image](https://cloud.githubusercontent.com/assets/7633344/16627735/9c008afe-437c-11e6-9a19-13fed018f2a3.png)
Plinko-Probability
![image](https://cloud.githubusercontent.com/assets/7633344/16627755/b1af6e60-437c-11e6-9923-82779a0222f4.png)
Pendulum-Lab
![image](https://cloud.githubusercontent.com/assets/7633344/16627813/e81d36ee-437c-11e6-805d-ab977f015a03.png)
Gravity Force Lab
![image](https://cloud.githubusercontent.com/assets/7633344/16627911/5244a19c-437d-11e6-9433-7c07a174a206.png)

**Comment by veillette** [comment] 2016-07-06 18:39
Here is what the number control looks like.

![image](https://cloud.githubusercontent.com/assets/7633344/16630185/4c7351b4-4387-11e6-9de6-93bbb293db99.png)

**Comment by veillette** [comment] 2016-07-06 18:46
Bending Light has a separate design

![image](https://cloud.githubusercontent.com/assets/7633344/16630441/68140f8e-4388-11e6-8bbd-12765a95092b.png)

**Comment by pixelzoom** [comment] 2016-07-07 18:42
This is a duplicate of https://github.com/phetsims/scenery-phet/issues/217.

**Comment by pixelzoom** [comment] 2016-07-07 18:44
Dev meeting: Closing, will track in #217.

**Closed by pixelzoom** 2016-07-07 18:44 UTC
Labels: meeting:developer
