### ISSUE TITLE
interaction bug with ProbeNode and crosshairs

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#204] opened 2015-11-02 23:31 UTC
Noticed in beers-law-lab and ph-scale.

If you use a ProbeNode with crosshairs, you can't grab the probe anywhere within the crosshairs. This differs from the behavior of image files, and is a problem (says @ariel-phet).  

It can be fixed in ProbeNode.crosshairs by adding a scenery.Circle, filled with 'rgba(0,0,0,0)'. @samreid do you agree with this method of fixing?

This must be fixed before publishing additional RCs for beers-law-lab (https://github.com/phetsims/tasks/issues/40) and concentration (https://github.com/phetsims/tasks/issues/406).  Publication of these is desired ASAP on 11/3/15, so high priority.

**Comment by pixelzoom** [comment] 2015-11-03 02:05
Or perhaps this Circle should be added to the main geometry, so that each sensor type (crosshairs and custom) doesn't need to deal with it?

**Comment by samreid** [comment] 2015-11-03 02:19
I thought the best way to fix this might be to set mouseArea = touchArea to the outer path shape.  Looking into it.

**Comment by samreid** [comment] 2015-11-03 02:29
I'm running into troubles with setting the mouseArea and touchArea.  First problem is a scenery exception where Node is assuming that a Node already has parents before changing its mouseArea/touchArea.  I tried commenting that out and it still didn't work as expected--I may not understand the scenery touchArea/mouseArea details.  For now I'll commit a blank shape that covers the entire area.  It would be good to get help from @jonathanolson or @pixelzoom to get the mouseArea/touchArea working as a better long term solution.

**Comment by samreid** [comment] 2015-11-03 02:31
I should also mention why I implemented the change as above instead of with a circle--by using the outline of the shape we can guaranteed there are no seams or holes.  Though one reason I would like to get mouseArea/touchArea working for the long term is to keep the scene graph more pruned.  @pixelzoom over to you for discussion.

**Comment by samreid** [comment] 2015-11-03 03:09
My mistake, I was trying to set mouseArea before calling Node.call(this,...).  New fix coming soon.

**Comment by samreid** [comment] 2015-11-03 03:10
Fixed above, and tests nicely on OSX Chrome.  I'll report back after testing on touch as well.

**Comment by samreid** [comment] 2015-11-03 03:12
The touch area is not working as expected--I'm looking into it.

**Comment by samreid** [comment] 2015-11-03 03:16
This code fixed the mouse area but not the touch area:
```js
    Node.call( this, {
      children: children,
      mouseArea: outline,
      touchArea: outline
    } );
```

@pixelzoom @jbphet @jonathanolson what am I doing wrong here?

**Comment by samreid** [comment] 2015-11-03 06:37
Ah it appears there is a line in Beers Law Lab that is interfering with the touch area.  ConcentrationMeterNode.js line 182 reads:

```js
thisNode.touchArea = Shape.rectangle( thisNode.x - dx, thisNode.y - dy, thisNode.width + dx + dx, thisNode.height + dy + dy );
```

If I comment out that line, then the interior of the touch area works properly.  I'll leave this assigned to @pixelzoom to decide what to do next, some options:
1. Delete line 182.  This would use the touch area as specified in ProbeNode.  It is not expanded by 25% but perhaps that is OK since swipe-to-snag is enabled for the ProbeNode anyways.
2. Change ProbeNode to increase the touch area by 25%.  This could be done for the outline shape or for its bounding box.
3. Change ConcentrationMeterNode to increase the touch area size by 25% (or the bounding box increased by 25%).  This would override the value in ProbeNode.
4. Something else.

**Comment by samreid** [comment] 2015-11-03 06:39
Also, is this an issue with other usages of the ProbeNode and its touch area?

**Comment by pixelzoom** [comment] 2015-11-03 15:41
Is this also a problem for ATDetectorNode, which sets touchArea in the same manner on line 181?

I'm also not clear on why this should be "interfering" with the touchArea. Should this be simply overriding ProbeNode's default touchArea?  Why is that not OK?

**Comment by pixelzoom** [comment] 2015-11-03 15:43
I'm not clear on why this should be "interfering" with the touchArea. Should this be simply overriding ProbeNode's default touchArea?  Why is that not OK?

And yes - if this is a problem is beers-law-lab.ConcentratioNode, then it will also be a problem in beers-law-lab.ATDetectorNode and ph-scale.MacroPHNode (and possibly other sites that I'm not aware of.)

**Comment by samreid** [comment] 2015-11-03 15:45
> I'm not clear on why this should be "interfering" with the touchArea. Shouldn't this be simply overriding ProbeNode's default touchArea? Why is that not OK?

I was also surprised to see this interference, and not sure of the cause.

**Comment by samreid** [comment] 2015-11-03 15:55
@pixelzoom and I determined that the incorrect coordinate frame was being used to set the touch area, it is remedied in the above commit.

**Closed by samreid** 2015-11-03 15:55 UTC
Labels: bug, high-priority, Summer 2015 redeploy
