### ISSUE TITLE
Hear duplicate alerts inside Sonification Wrapper

### ISSUE THREAD

**Issue by terracoda** [phetsims/scenery-phet#351] opened 2018-02-28 18:45 UTC
With Voice Over on, I hear duplicate alerts when using any of the sliders in the Ohm's Law and Resistance and a Wire sims.

**Comment by jessegreenberg** [comment] 2018-02-28 19:12
@terracoda are you able to reproduce this in master on phettest or is this just in the sonification wrapper? Can you provide macOS and Safari version numbers? Does this happen all the time or intermittently?

In macOS 10.13.3 and Safari 11.0.3 with VoiceOver,  here is what I am seeing:
- If I move one step with the keyboard single alert as expected
- If I quickly move several steps in a row, very sometimes VoiceOver will queue the alerts and I will hear them in order, usually 2 alerts at a time.
- ~3 times while testing this morning I was able to get a repeated alert, now I can't reproduce it.

**Comment by terracoda** [comment] 2018-02-28 19:14
Just on sonification wrapper. I tested phettest and things did not repeat.

**Comment by jessegreenberg** [comment] 2018-02-28 19:40
I just found a way to reproduce this (only in sonification wrapper). If the sim is launched before VO is turned on, all alerts repeat.

**Comment by jessegreenberg** [comment] 2018-02-28 19:41
I verified this happens in all iframes by reproducing the problem here:
https://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.5.0-dev.2/phet/resistance-in-a-wire_all_iframe_phet.html

Refreshing browser makes problem go away.

**Comment by jessegreenberg** [comment] 2018-02-28 19:55
I was able to isolate and reproduce this problem in a very simple JSFiddle https://jsfiddle.net/u1h1yc59/3/

@terracoda I am going to submit a bug report to Apple (in phetsims/a11y-research#93) and close this issue, but you believe this wasn't the root of the problem or if this bug resurfaces in another context please let me know.

**Closed by jessegreenberg** 2018-02-28 19:55 UTC
