### ISSUE TITLE
Modernize the Bucket Code 

### ISSUE THREAD

**Issue by davisv007** [phetsims/scenery-phet#308] opened 2017-05-17 20:00 UTC
Currently, we are working on porting Fractions Intro from Java to JavaScript. One of the behaviors we need to implement from the original program is the dynamic labeling for the bucket. Recently, we attempted to add a basic bucket to the screen of our project along with a test label, leading to the creation of Issue #307.
Either from foresight or coincidence,  @jbphet brought up that the Bucket code does not allow adding anything other than text as a label to the bucket, and if we needed this functionality, we should create an issue and work together to make it happen. 

![image](https://cloud.githubusercontent.com/assets/8039583/26173098/a2573530-3b18-11e7-8045-ed3708f1cdf6.png)

As you can see the Bucket Label in the original program changes depending on the denominator...

![image](https://cloud.githubusercontent.com/assets/8039583/26173013/55045984-3b18-11e7-8268-db06311d0ffc.png)

as well as the shape.

![image](https://cloud.githubusercontent.com/assets/8039583/26173150/d5dd124e-3b18-11e7-9f55-e0d8a3ac2d93.png)

**Comment by ariel-phet** [comment] 2017-05-17 20:31
@davisv007 please note that an issue with no assignee (or at least not the dev meeting tag) is unlikely to be addressed. If in doubt please assign to me.

**Comment by veillette** [comment] 2017-05-17 21:36
@davisv007 could assign this issue, since it it doesn't have permission on this repo. (and it is best that he does not at this stage).  Since at @jbphet works on #307, i'm assigning this to him.

**Comment by ariel-phet** [comment] 2017-05-17 21:39
Ah, understood @veillette

**Comment by veillette** [comment] 2017-05-17 21:41
FYI, @jbphet ,  @davisv007 and I have been working on a FrontBucket that can display a node.
We don't want to commit anything to Scenery-PhET, so we'll paste our code for FrontBucket when we have a good working draft.

**Comment by jbphet** [comment] 2017-05-17 22:56
Sounds good @veillette.  For an example of a common code node that takes a node that it essentially uses as a label, please the see the `titleNode` option in `AccordionBox`.  You don't need to add all the options for positioning or anything, at least not yet, but it will be good to look at the basic approach.  Also, it sounds like you might be changing this label node dynamically, so there may need to be an option that causes code to be hooked up that repositions the label on a bounds change.

**Comment by samreid** [comment] 2017-05-18 15:25
@jbphet does this still need to be marked for developer meeting?

**Comment by jbphet** [comment] 2017-05-18 17:08
@ariel-phet marked it, and since I don't know why, I'll leave it.

**Comment by ariel-phet** [comment] 2017-05-18 17:16
@jbphet marked it because it originally did not have someone assigned, unmarking

**Comment by davisv007** [comment] 2017-05-18 18:00
@jbphet please consider these changes we made to BucketFront.js I don't think they will affect existing projects. We looked at build-an-atom, and curve-fitting, and they seemed to work the same as before.

https://gist.github.com/davisv007/b48a7a93e333ff2a8a9674bd77eee2cd

Points of interest at the following line numbers:
* 33-37
* 44
* 46-49
* 52
* 55-57
* 67-83

Let me know if you think this is a good approach.

**Comment by jbphet** [comment] 2017-05-19 22:28
In general, the approach in https://gist.github.com/davisv007/b48a7a93e333ff2a8a9674bd77eee2cd looks reasonable for now.  I have some specific comments below.  Once this version is working, please reassign the problem to me and I'll refactor the code that currently makes use of the `captionText` option to move all labeling into the view.  Strictly speaking, the Bucket shouldn't be carrying around its label text.

Comments on the gist shared above:
+ Having a parent node for the label seems unnecessary to me.  Why not just have 'labelNode', and add it to the BucketFront node directly?  Since a reference will be kept, it can easily be removed when `setLabel` is called.
+ The center of the node can be set in a single line of code, something like `newLabelNode.center = this.transformedShape.bounds.getCenter()` (I don't think this was available when the code was originally written, which is why it wasn't done that way originally).  However, there may be a problem here, and you'll need to try this out to see for sure.  The original code creates the shape, then positions the label, then sets the translation.  Your changes behave similarly.  This may make the bounds move, so the result would be that the original label is positioned correctly, but subsequent labels are 'double transformed'.  If this is the case, you'll need to set the center of the label node based on 1/2 the width and height of the transformedShape's bounds.

Please go ahead with the implementation, being sure to regression test all simulations that use this before committing, and also making sure to lint it.  Once you've committed it, assign the issue to me and I'll review right away, and will look into refactoring other usages as time permits.

**Comment by davisv007** [comment] 2017-05-22 17:55
@jbphet, I looked at your comments and made changes to the original gist. I believe I addressed your first concern but I had trouble understanding the second concern. I centered the node in one line as you suggested (which worked) and then attempted to center it using the bounds width /2 etc. which did not work so I reverted back to the one liner.

@veillette pushed the new BucketFront in deb95a1. We tested affected simulations like buildanatom, buildamolecule, as well as curvefitting and they all the seemed to work normally. 

 In my latest [commit](https://github.com/phetsims/fractions-intro/commit/bffba2d50aecc1a82cc7c738099e9b44e8f65d4d), I added a BucketNode to IntroScreenView whose label is linked with the representation panel using the new setLabel method. 

Let me know what you think!

**Comment by jbphet** [comment] 2017-05-26 23:25
This generally looks good.  I have a few comments:

+ It looks like it would have problems if the label were set to null on construction or by calling the `setLabel` method.  It should be able to handle this case.
+ Having `transformedShape` as an attribute on the object is pretty unconventional.  It would be easier to maintain the node that represents the actual front of the bucket as the attribute, and reference it in in the `setLabel` method.
+ Anything that is visible on the object, such as `transformedShape` is now or `bucketFrontNode` may be in the future, should have a visibility annotation.
+ The scaling code in `setLabel` could be simplified by setting the `maxWidth` and `maxHeight` attributes of the label node instead of what's being done now.

**Comment by davisv007** [comment] 2017-06-01 16:02
Checklist for myself. Checked items may not be committed yet. 

- [ ] setLabel method handles null.

- [ ] Maintain the node that represents the actual front of the bucket as the attribute, and reference it in in the setLabel method.

- [ ] Anything that is visible on the object should have a visibility annotation.

- [ ] Simplify the scaling code in setLabel by setting the maxWidth and maxHeight attributes of the node

**Comment by davisv007** [comment] 2017-06-02 21:05
@jbphet about your 3rd point...

in line 61 or BucketFront, should this.translate be public or private? 

Besides this, I think I was able to address your other points.

**Comment by jbphet** [comment] 2017-06-02 21:15
In the current master version, line 61 of `BucketFront.js` looks like this:

```js
    this.translation = modelViewTransform.modelToViewPosition( bucket.position );
```

The translation member is defined in `Node.js` and is inherited by `BucketFront`, so there is no need to specify any sort of visibility here.  In this specific case, this actually invokes an ES5 setter (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/set), which ends up invoking a `set` function which ultimately sets the visual position of the `BucketFront` node.

@davisv007 - I hope that answers your question, let me know if not and we can discuss more.

**Comment by davisv007** [comment] 2017-06-07 17:45
Okay, @jbphet, I think our revisions are complete. Please review them and let us know.

**Comment by veillette** [comment] 2017-07-05 20:39
The work on the bucket label is done. Assigning back @jbphet for review.

**Comment by jbphet** [comment] 2017-07-18 16:56
Looks good to me, closing.

**Closed by jbphet** 2017-07-18 16:56 UTC
Labels: dev:enhancement
