### ISSUE TITLE
FaceNode smile truncated in screenshot

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#218] opened 2016-02-17 19:42 UTC
![image](https://cloud.githubusercontent.com/assets/679486/13122387/dd3f07ba-d573-11e5-97e6-5bfd998805c2.png)

Discovered during https://github.com/phetsims/build-an-atom/issues/120

@jonathanolson can you guess what is wrong here?

**Comment by jonathanolson** [comment] 2016-02-17 19:50
Possibly a Scenery or browser Canvas issue. What browsers does it happen with, and where's the URL where I can reproduce?

**Comment by samreid** [comment] 2016-02-17 19:54
You can test it here: http://localhost/phet-io/html/wrappers/screenshot.html?sim=build-an-atom

I saw the problem in Chrome Version 48.0.2564.109 (64-bit), only for the frown, the smile rendered OK in the screenshot.

**Comment by jonathanolson** [comment] 2016-02-17 20:36
Looks like Chrome-specific line-cap issue, see https://github.com/phetsims/scenery/issues/514.

**Comment by pixelzoom** [comment] 2017-04-27 03:35
I am no longer able to reproduce this, see screenshot below. (Chrome 58, Mac OS 10.11.6). @samreid shall we close this issue?

![screenshot_234](https://cloud.githubusercontent.com/assets/3046552/25466829/314318a6-2ac8-11e7-99b2-709c2763a7a2.png)

**Comment by samreid** [comment] 2017-04-27 04:13
This comment describes the chrome version that fixed the problem, it seems we are good to go:
https://github.com/phetsims/scenery/issues/514#issuecomment-221955040

**Comment by samreid** [comment] 2020-05-21 21:56
There are still TODOs marked for this issue, discovered during https://github.com/phetsims/chipper/issues/946

**Comment by samreid** [comment] 2020-05-26 18:43
The remaining TODO is:

```js
// TODO if !enabled, cancel any interaction that is in progress, see https://github.com/phetsims/scenery-phet/issues/218
```

Unassigning until we return focus to this implementation.

**Comment by pixelzoom** [comment] 2021-02-23 16:42
The "remaining TODO" no longer exists.  Closing.

**Closed by pixelzoom** 2021-02-23 16:42 UTC
Labels: priority:4-low, type:bug
