### ISSUE TITLE
icon shifts on SoundToggleButton

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#329] opened 2017-08-09 22:41 UTC
When you click on SoundToggleButton, the speaker part of the icon shifts horizontally.  The speaker should remain stationary, and the bit to the right of the speaker should change.   This could probably be accomplished by padding the icon.

See for example https://phet.colorado.edu/sims/html/plinko-probability/latest/plinko-probability_en.html

Assigning to @ariel-phet to decide how important this is.

**Comment by pixelzoom** [comment] 2017-08-09 22:42
Might be a little tricky to pad the icons, since this button uses font-awesome icons.

**Comment by ariel-phet** [comment] 2017-08-29 22:59
Assigning to @jbphet and @jessegreenberg since this button will likely get more use as we work with sonfication. Probably more in the @jbphet wheelhouse since he did lots of work on buttons, but I will leave you two to decide on who will work on it, or feel free to collaborate

**Comment by jbphet** [comment] 2017-08-30 15:58
The issue isn't that the icon shifts, it's that the "sound off" icon is a little bit narrower than the "sound on" icon, and both are centered on the button.

![image](https://user-images.githubusercontent.com/3082831/29882185-81701cb2-8d69-11e7-97d3-4c63335a152e.png)

I just looked at the code for `SoundToggleButton`, and there is some scaling being done, so I'll take a look and see if this can be fixed with more precise scaling.

**Comment by pixelzoom** [comment] 2017-08-30 16:20
Understood.  I should have said "perceived shift".

**Comment by pixelzoom** [comment] 2017-08-30 16:32
Left justifying the icons on the button should solve the problem.

**Comment by jbphet** [comment] 2017-09-01 21:14
I made a one-line change that appears to address the issue by making the icons the same width.  @pixelzoom - please have a look and close if you're okay with it.  Left justifying would probably have worked too.

**Comment by pixelzoom** [comment] 2017-09-01 21:35
2 changes in the above commit:
• The 1-line fix was indeed effective, but not obvious, so worth documenting (which I added).
• Creation of the 2 icons was somewhat interleaved, so I cleaned that up.

Back to @jbphet for a quick review. Feel free to close.

**Comment by jbphet** [comment] 2017-09-05 15:30
Looks good, thanks @pixelzoom.  Closing.

**Closed by jbphet** 2017-09-05 15:30 UTC
Labels: design:general, priority:4-low
