### ISSUE TITLE
Allow listeners to be attached to just the body + nozzle parts

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#660] opened 2021-01-31 04:10 UTC
In order to support the design for Bending Light (for https://github.com/phetsims/bending-light/issues/339), we would like to attach a listener to the body + nozzle rather than the entire LaserPointerNode.  I think this means we would like to make a new child that combines the bodyNode + nozzleNode accessible.

**Comment by samreid** [comment] 2021-01-31 18:11
Implemented in the commit, tested in https://github.com/phetsims/bending-light/issues/339 and a number of other sims that use LaserPointerNode.  Ready for review.  One question for the reviewer: instead of making `bodyAndNozzleNode` `@public`, should we add `addBodyAndNozzleNodeInputListener` methods?  Assigning to the author of LaserPointerNode for review.

**Comment by pixelzoom** [comment] 2021-02-01 00:14
I haven't reviewed this yet, but a regression seems to have slipped into LaserPointerNode.  The beam location is now forward of the optional lens (`hasGlass: true`), which is not correct.   See screenshot below.  Back to @samreid before I review.

In scenery-phet demo:

<img width="359" alt="screenshot_840" src="https://user-images.githubusercontent.com/3046552/106402574-5b94b680-63e7-11eb-88e9-91e370013d18.png">

**Comment by samreid** [comment] 2021-02-01 02:41
I shifted the source of the light so it will go through the lens.  I didn't track down the exact origination of this problem, but it appears it has been around for a while.

**Comment by pixelzoom** [comment] 2021-02-02 18:21
I'm trying to figure out why this changed is needed.  

Looking at phetsims/bending-light#339, you're using this feature in LaserNode, which uses LaserPointerNode via composition.  You're conditionally adding a decoration to (`knobImage`), and then using `bodyAndNozzleNode` for touch area and input listener target Node:

```js
const knobImage = new Image( knobImageData, { scale: 0.58, rightCenter: laserPointerNode.leftCenter } );
    knobImage.touchArea = knobImage.localBounds.dilatedXY( 15, 27 ).shiftedX( -15 );
    hasKnob && laserPointerNode.addChild( knobImage );
    laserPointerNode.translate( laserPointerNode.width, laserPointerNode.height / 2 );
    if ( !hasKnob ) {
      laserPointerNode.bodyAndNozzleNode.touchArea = laserPointerNode.bodyAndNozzleNode.bounds.dilated( 8 ).shiftedX( -8 );
    }

    const translationTarget = hasKnob ? laserPointerNode.bodyAndNozzleNode : knobImage;
    const rotationTarget = hasKnob ? knobImage : laserPointerNode.bodyAndNozzleNode;
```

It's not clear to me - why can't you just use `laserPointerNode`?

**Comment by pixelzoom** [comment] 2021-02-02 18:30
Discussed with @samreid on Slack.  There is no need for this feature if we do `laserPointerNode.addChild( knobImage )` do `this.addChild( knobImage)`, and it's OK if the laser can be dragged by its button.   There is precedent for being able to drag by the button - see dropper in pH Scale - so if that's _not OK_, I'd like to hear why it's desirble in pH Scale, but not in Bending Light.

**Comment by samreid** [comment] 2021-02-02 18:42
I reverted the change to LaserPointerNode that made body+nozzle public, and I updated bending light's LaserNode accordingly.  @pixelzoom and I discussed adding the `knobImage` to `this` instead of to the `laserPointerNode` but that did not appear to be necessary, the input listeners seem to be doing the right thing with the knob a child of the `laserPointerNode`.

Also, for unknown reasons, the laser still cannot be dragged by the button.

@pixelzoom want to take a look?

**Comment by pixelzoom** [comment] 2021-02-02 18:58
> Also, for unknown reasons, the laser still cannot be dragged by the button.

The input listener on the button would need to be `attach: false`.  And it looks like we did that in EyeDropperNode:

```js
    const button = new RoundMomentaryButton( false, true, this.dispensingProperty, {
      baseColor: 'red',
      radius: 18,
      listenerOptions: {
        // We want to be able to drag the dropper WHILE dispensing, see https://github.com/phetsims/ph-scale/issues/86
        attach: false
      },
      tandem: options.tandem.createTandem( 'button' )
    } );
```

So something similar would need to be added to `const buttonOptions` in LaserPointerNode.

**Comment by samreid** [comment] 2021-02-02 19:09
@arouinfar should the laser pointer in Bending Light be able to be dragged by the button?

**Comment by arouinfar** [comment] 2021-02-03 16:01
@samreid I don't think the laser needs to be draggable by the button. It may also end up being accidentally dragged by users on touch devices.

For PhET-iO we are going to want to be able to make the body of the lasers pickable:false while keeping the button interactive. The same issue came up in pH Scale, see https://github.com/phetsims/scenery/issues/1041 and https://github.com/phetsims/scenery/issues/1116. I don't know if that has any impact on the current issue, but I want to make you aware of this design requirement in case it does.

**Comment by samreid** [comment] 2021-02-03 16:33
> For PhET-iO we are going to want to be able to make the body of the lasers pickable:false while keeping the button interactive.

@pixelzoom will our proposed strategy work with that design constraint?

**Comment by pixelzoom** [comment] 2021-02-03 16:38
No, it will not.  And it does not currently work that way in ph-scale, see https://github.com/phetsims/ph-scale/issues/141.

I'm also of the opinion that setting pickable is the wrong way to address this. We should be disabling specific input listeners, so that we can easily support exactly this type of requirements.

**Comment by samreid** [comment] 2021-02-03 16:43
In https://github.com/phetsims/scenery/issues/1041#issuecomment-726290053 it was argued:

> Add enabledProperty to listeners. This is not a good solution because you may have to do one for the drag listener, and another for the keyboard listener. This in general would be clunky for the PhET-iO API client (studio user).

Is there a way to pair the pointer input with the keyboard input so they can be disabled together?

**Comment by pixelzoom** [comment] 2021-02-03 16:50
@samreid It feels like we're now veering off into a discussion that belongs in phetsims/scenery#1041 (comment).  I don't have time for that right now, and I think it needs to involve more parties.

I recommend closing this issue (since the non-PhET-iO requirments are met), and opening a new issue for the PhET-iO requirement that @arouinfar mentioned (similar to phetsims/ph-scale#141);

**Closed** 2021-02-03 17:36 UTC
Labels: status:ready-for-review
