### ISSUE TITLE
investigate unexpected garbage collection behavior

### ISSUE THREAD

**Issue by jbphet** [phetsims/scenery-phet#330] opened 2017-08-14 20:15 UTC
I recently needed to add a dispose function for the new reusable keypad component, see https://github.com/phetsims/scenery-phet/issues/283.  I added a test harness to the scenery-phet demo that removed the keypad and called its dispose function.  Initially, this didn't appear to work - before and after memory snapshots revealed that the keypad was not being garbage collected.  After quite a bit of experimentation, I found that setting the internal reference to the keypad to null solved the problem.  The code snippet below illustrates:

```js
    var removeKeypadFromScreenButton = new RectangularPushButton( {
      content: new Text( 'Remove Keypad (tests dispose)' ),
      baseColor: '#73DC69',
      listener: function() {
        positiveAndNegativeFloatingPointKeyPad.clear();
        positiveAndNegativeFloatingPointVBox.removeChild( positiveAndNegativeFloatingPointKeyPad );
        positiveAndNegativeFloatingPointKeyPad.dispose();
        positiveAndNegativeFloatingPointKeyPad = null; // !! THIS IS THE LINE THAT MAKES THE KEYPAD GET GARBAGE COLLECTED.
        positiveAndNegativeFloatingPointVBox.removeChild( positiveAndNegativeFloatingPointClearButton );
        positiveAndNegativeFloatingPointClearButton.dispose();
        positiveAndNegativeFloatingPointVBox.removeChild( positiveAndNegativeFloatingPointClearOnNextKeyPressCheckBox );
        positiveAndNegativeFloatingPointClearOnNextKeyPressCheckBox.dispose();
        positiveAndNegativeFloatingPointVBox.removeChild( removeKeypadFromScreenButton );
        removeKeypadFromScreenButton.dispose();
      }
    } );

```
@jonathanolson and I looked at this together, and he wanted to investigate a bit further and better understand why this is necessary.  The immediate problem of testing the Keypad's dispose function is resolved, but this might have some implications around how we avoid, investigate, and fix memory leaks.

**Comment by jbphet** [comment] 2017-08-14 20:19
Version b47f90ab81d5fabb758e686cf57d4ccaa6d7c864 exhibits the behavior.  To duplicate,

1. Run the scenery-phet demo
2. Go to the "Components" screen and select "Keypad"
3. Take a memory snapshot
4. Press the "Remove keypad (tests dispose)" button
5. Take another memory screenshot

If this test is run with the line `positiveAndNegativeFloatingPointKeyPad = null;` in place, there will be two instances of `Keypad` in the 2nd memory screenshot.  Comment out this line a re-run the test, and you'll see 3 instances of `Keypad`.

**Comment by jonathanolson** [comment] 2017-08-15 01:31
So I've taken an in-depth look at this, and have the following to note (for the developer meeting):

The following will leak both (a) and (b), since sibling closures share their contexts (variables in the current scope that are tracked) and contexts contain references to their parent contexts.
```js
window.outer = (function(){
  // Context for 'outer' created

  var a = new scenery.VBox( {} );
  return (function inner(){
    // Context for 'inner' created,
    // contains reference to parent (outer) context

    var b = new scenery.HBox( {} );

    function useless1() {
      // Variable 'a' added to 'outer' context.
      return a;
    }
    function useless2() {
      // Variable 'b' added to the 'inner' context
      return b;
    }

    // Holds a reference to the 'inner' context
    function useless3() {}
    return useless3;
  })();
})();
```
Thus in memory, the references that hold this:
```
useless3
  'inner' context
    b
    'outer' context
      a
```

References: http://point.davidglasser.net/2013/06/27/surprising-javascript-memory-leak.html, http://mrale.ph/blog/2012/09/23/grokking-v8-closures-for-fun.html, and confirmed with testing.

I've looked into a number of methods of working around this, and the most general seems to be just setting the variable to a different value (usually `null`). Thus before `useless3` is declared, the following would set the value of a/b to `null` in the contexts:
```js
a = null;
b = null;
```

I'd generally recommend that approach of null-ing references when needed (and as done by @jbphet for this issue), although sometimes adding an in-between closure (so that adjacent functions don't contain references) may work, e.g.:
```js
// THIS LEAKS
window.example = (function(){
  var a = new scenery.VBox( {} );

  function useless() {
    return a;
  }

  return function() {};
})();

// This does not leak
window.example = (function(){

  // The context for this function closure is not referenced by the returned anonymous function.
  (function(){
    var a = new scenery.VBox( {} );

    function useless() {
      return a;
    }
  })();

  return function() {};
})();
```

Marking for developer meeting to go over this and its potential implications for leak-free development.

**Comment by pixelzoom** [comment] 2017-08-15 15:14
Here’s a more thorough explanation of this type of leak, and how to fix them: 
https://blog.meteor.com/an-interesting-kind-of-javascript-memory-leak-8b47d2e7f156

**Comment by pixelzoom** [comment] 2017-08-17 18:49
Discussed at 8/17/17 dev meeting.  Closing.

**Closed by pixelzoom** 2017-08-17 18:49 UTC
