### ISSUE TITLE
TimeControlNode should expose the position of the playPause button

### ISSUE THREAD

**Issue by veillette** [phetsims/scenery-phet#564] opened 2019-12-14 19:16 UTC
I very much like this new TimeControlNode, particularly how the options are passed very cleanly.

In the process of converting our time control buttons to TimeControlNode, https://github.com/phetsims/collision-lab/issues/43, we determine that it would be useful to add some additional methods for laying out this node.

For instance, Collision lab assumes that the Play/Pause Button is horizontally centered with the middle of the playgrid. However with the addition of the slow/normal radioButtons, the Play/Pause Button is no longer the center of the node.
Can we expose the XCenter of the play pause button with respect to the left via a public method?

**Comment by jessegreenberg** [comment] 2019-12-27 16:03
This sounds important. I added a function above to get the center of the PlayPauseButton. Usage in collision-lab might look like 

```js
      timeControlNode.centerX = gridNode.centerX + ( timeControlNode.centerX - timeControlNode.getPlayPauseButtonCenter().x );
```

I considered changing TimeControlNode origin to be the center of the PlayPauseButton so that centering might be more simple
```js
      timeControlNode.x= gridNode.centerX;
```

But that seemed more intrusive to TimeControlNode and I wasn't sure if positioning relative to center of PlayPauseButton would be the typical layout.

@veillette do you think https://github.com/phetsims/scenery-phet/commit/9032047c0138a45707045cd7a7b1f17710b04b75 will work?

**Comment by brandonLi8** [comment] 2020-05-18 17:02
@jessegreenberg I'm not sure when `setPlayPauseButtonCenter` was added but it's related to this issue so I am adding this here.

The documentation of this method states that this method
```
  /**
   * Translate this node so that the center of the PlayPauseButton is at the specified point in the parent
   * coordinate frame.
   * @public
   *
   * @param {Vector2} center
   */
```

However, using it in `collision-lab` (https://github.com/phetsims/collision-lab/issues/43)),

my use case is:
```
  collisionLabTimeControlNode.setPlayPauseButtonCenter( new Vector2( playAreaNode.centerX, collisionLabTimeControlNode.centerY ).subtract( collisionLabTimeControlNode.leftTop ) );
```

The `subtract( collisionLabTimeControlNode.leftTop )` at the end seems to suggest that the `setPlayPauseButtonCenter` positions the center in the TimeControlNode's **local** coordinate frame. If it where positioning in the TimeControlNode's **parent** coordinate frame, wouldn't it look like 

```
collisionLabTimeControlNode.setPlayPauseButtonCenter( new Vector2( playAreaNode.centerX, collisionLabTimeControlNode.centerY ) );
```


Furthermore, in the `setPlayPauseButtonCenter` method, there is
`    const distanceToCenter = this.playPauseStepButtons.getPlayPauseButtonCenter().minus( this.center );` The `this.playPauseStepButtons.getPlayPauseButtonCenter()` is in the TimeControlNode's local coordinate frame where `this.center` is the TimeControlNode's parent coordinate frame, which makes the distanceToCenter difference off.

My proposal is to either change the implementation so that it positions the center of the PlayPauseButton in the TimeControlNode's parent coordiante frame or to change the documentation. @jessegreenberg what do you think?

**Comment by jessegreenberg** [comment] 2020-05-18 20:41
Thanks @brandonLi8,you are correct. 

> his.playPauseStepButtons.getPlayPauseButtonCenter() is in the TimeControlNode's local coordinate frame where this.center is the TimeControlNode's parent coordinate frame, which makes the distanceToCenter difference off.

That was fixed in https://github.com/phetsims/scenery-phet/commit/65d2e1a66e1e99faab47e241542290a65f392ea9.  The usage in collision-lab would change to https://github.com/phetsims/collision-lab/commit/fa176f4808286102aa50bbc264848142c7d396bd. @brandonLi8 can you please take a look and make sure this fixes the problem?

**Comment by brandonLi8** [comment] 2020-05-18 21:10
@jessegreenberg thanks! The problem is fixed in collision lab. Closing.

**Closed by brandonLi8** 2020-05-18 21:10 UTC
Labels: status:ready-for-review
