### ISSUE TITLE
Support other font styles in MathSymbolFont

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#648] opened 2020-12-01 19:11 UTC
MathSymbolFont is the font used for math symbols.  It uses these options, which cannot be changed:

```js
family: '"Times New Roman", Times, serif',
style: 'italic'
```

In Fourier, I've discovered that there are some math symbols (pi, sigma,...) that look best in 'normal' (not 'italic') MathSymbolFont.  So I'm going to add the ability to override the default style, both in the constructor and in `getRichTextMarkup`.

**Comment by pixelzoom** [comment] 2020-12-01 19:29
Done in the above commit.  

In `getRichTextMarkup`, I replaced the `<i>` tag with the `font-style` attribute. 

I'm using this feature now in Fourier, for example in FMWSymbols.js:

```js
  CAPITAL_SIGMA: MathSymbolFont.getRichTextMarkup( '\u03a3', 'normal' ), // summation symbol
  PI: MathSymbolFont.getRichTextMarkup( '\u03c0', 'normal' ), // pi
```

@ariel-phet please assign someone to review. While many sims use MathSymbolFont, the only other developer currently using `getRichTextMarkup` is @jbphet in number-line-distance.

**Comment by pixelzoom** [comment] 2020-12-01 19:35
One more change... In the above commits, I added validation of the `style` argument to `getRichTextMarkup`.  I thought this was important since this method is not creating a Font, and we're relying on the DOM to process the `font-style` attribute.

**Comment by ariel-phet** [comment] 2020-12-01 19:36
@jbphet said he could review since this looks pretty quick.

**Comment by jbphet** [comment] 2020-12-02 18:46
Looks good to me.  Very good actually.  It seems like a valid way to address the problem, the commits seem reasonable, and the sigma and pi characters look good in Fourier in non-italicized style.  I also did a quick regression test of the usages in Expression Exchange and Number Line: Distance, and things look fine there.  Closing.

**Closed by jbphet** 2020-12-02 18:46 UTC
Labels: dev:enhancement, status:ready-for-review
