### ISSUE TITLE
Tweak alerting delay/interval values

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#491] opened 2019-04-23 19:30 UTC
From https://github.com/phetsims/scenery-phet/issues/490 and https://github.com/phetsims/scenery-phet/issues/485 we made some changes to the alerting system. There are some numbers that are likely worth tweaking, but they should be done in conjunction with each other to assure that we get the desired effect. @jessegreenberg and I discussed and we think it would be best to have alerts move through the queue and AriaHerald as quickly as possible by default, recognizing that we can always specify larger values for inidividual Utterance instances. So we propose the following changes:

* The two `setTimeout` calls in AriaHerald have a delay of `0`
* `UtteranceQueue` no longer has a stepInterval, and instead is just stepped every frame (via a listener on timer)
* `Utterance.alertStableDelay` defaults to a smaller value than 500.

We tested briefly on NVDA and JAWS with chrome/firefox and things seems like they were moving in a good direction. We will also note in the a11y-dev channel to be on the look out for changes to how alerts sound once we make these changes.

**Comment by zepumph** [comment] 2019-04-23 20:08
I posted in slack:

>Heads up, @jessegreenberg and I just did some major tweaking to the timing of alerts, please help us be diligent and report any strangeness or questions to https://github.com/phetsims/scenery-phet/issues/491

**Comment by jessegreenberg** [comment] 2019-04-23 21:31
Each of https://github.com/phetsims/scenery-phet/issues/491#issue-436352858 was completed in https://github.com/phetsims/scenery-phet/commit/7353071eaf03ea937868bc826fd951c50f2f340b, so lets test on 

- [ ] iOS 12 VO
- [ ] Firefox + NVDA
- [ ] Chrome + JAWS
- [ ] macOS VO

And if all sounds well I think this issue can be closed.

**Comment by jessegreenberg** [comment] 2019-04-23 21:35
I just tested ohms-law on my desktop with NVDA and Firefox and I am missing alerts ~15 percent of the time, I don't remember that from before this change.

**Comment by jessegreenberg** [comment] 2019-04-23 21:46
When I bump the timeouts in ariaHerald back up to 200 ms I can no longer produce the issue.

**Comment by jessegreenberg** [comment] 2019-04-23 21:53
I changed the timing to:

```js
      // must be done asynchronously from setting hidden above or else the screen reader
      // will fail to read the content
      timer.setTimeout( () => {
        AccessibilityUtil.setTextContent( liveElement, textContent );

        // Hide the content so that it cant be read with the virtual cursor. Must be done
        // behind a delay,  setting hidden too quickly will prevent the screen reader from
        // speaking the alert at all. Using `hidden` rather than setting textContent works better
        // than clearing textContent on mobile VO, see https://github.com/phetsims/scenery-phet/issues/490
        timer.setTimeout( () => {
          liveElement.hidden = true;
        }, 200 );
      }, 0 );
```

And I am getting all alerts from NVDA in Firefox (testing the sim for ~2 minutes changing things as fast as I can with the keyboard). So it seems like as long as the delay before hiding is long enough we get everything, at least in NVDA.

**Comment by jessegreenberg** [comment] 2019-04-23 22:18
@terracoda or @KatieWoe can you please check master and make sure that alerts sound OK on macOS VoiceOver after this change?

**Comment by KatieWoe** [comment] 2019-04-23 22:52
Looked at adjusting sliders on Ohm's Law and it seemed ok

**Comment by zepumph** [comment] 2019-04-23 23:06
> So it seems like as long as the delay before hiding is long enough we get everything, at least in NVDA.

@jessegreenberg did you try waiting 100ms instead of 200? Just out of curiosity.

**Comment by jessegreenberg** [comment] 2019-04-23 23:46
It looks like 100ms also works. I had previously tried 10 -> 30 -> 50, and each of those had the issue consistently. I reverted to 200 and the issue seemed to go away. But 100ms also seems sufficiently long in FF with NVDA.

**Comment by jessegreenberg** [comment] 2019-04-23 23:48
I reduced to 100ms. We tested this change against each of our supported ATs on their platforms, so I believe this can be closed. @zepumph is there anything else for this issue?

**Comment by zepumph** [comment] 2019-04-24 00:16
Not from me thanks.

**Comment by zepumph** [comment] 2019-04-30 20:59
This may be causing https://github.com/phetsims/gravity-force-lab-basics/issues/121, we should reopen and see.

**Comment by jessegreenberg** [comment] 2019-05-01 15:05
I should have access to macOS VO now, I will see if I can figure out what VO dislikes in changes for this issue and #490.

**Comment by jessegreenberg** [comment] 2019-05-01 18:25
I only have access to macOS 10.10.5, but I confirmed that alerts are gone prior to https://github.com/phetsims/scenery-phet/commit/7a6c7c9936cb7178dc3088836a241ddffb959291 and return after.

**Comment by jessegreenberg** [comment] 2019-05-01 19:03
I updated the doc to indicate that 200 ms was also critical for VoiceOver.

@zepumph also said:

> We also noticed that we need to increase the alertStableDelay for the position sliders and mass number spinners. I wonder if we should do this by increasing the default (reverting the change in phetsims/scenery-phet#491) or just changing those specific usages in GFLB.

What about a specific subtype of Utterance for this (like ActivationUtterance in #492) that helps VoiceOver read alerts after aria-valuetext, like ValueChangeUtterance?

**Comment by zepumph** [comment] 2019-05-01 21:32
That sounds excellent

**Comment by jessegreenberg** [comment] 2019-05-01 22:08
@zepumph can you please review by using ValueChangeUtterance in gravity-force-lab and seeing if it resolves the issue?

**Comment by terracoda** [comment] 2019-05-28 09:40
@zepumph, the position sliders and the mass slider/numberpickers sound fine in GFL Basics!

**Comment by terracoda** [comment] 2019-05-28 09:40
@zepumph, is it safe to close this issue?

**Comment by zepumph** [comment] 2019-05-30 20:27
Looks good to me. @jessegreenberg anything else?

**Comment by jessegreenberg** [comment] 2019-05-31 23:16
Thanks for the review.

**Closed by jessegreenberg** 2019-05-31 23:16 UTC
Labels: status:ready-for-review
