### ISSUE TITLE
RichTextIO and MultiLineTextIO are 99% similar

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#392] opened 2018-07-28 03:17 UTC
See https://github.com/phetsims/scenery-phet/issues/323#issuecomment-408578854, is there some way to factor out or reuse this code?  Or is it better to be duplicated in this case?  @zepumph thoughts?

**Comment by zepumph** [comment] 2018-07-28 23:52
Expanding on this, what if we had a "GenericText" or something that could be the base type for all three texts, and the TextIO (potentially renamed) can extend that and add the font and maxwidth options. I see that besides those added public methods, all three are 99% similar. . .

**Comment by zepumph** [comment] 2018-07-28 23:54
I think that in meetings in the past we have talked about having TypeIO hierarchy necessarily diverge from the Type structure in order to limit the exposure of implementation details (i.e. three types of texts) I think, perhaps this warrants a dev meeting though.

**Comment by samreid** [comment] 2018-07-29 00:54
> Expanding on this, what if we had a "GenericText" or something that could be the base type for all three texts, and the TextIO (potentially renamed) can extend that

Did you mean GenericTextIO?

**Comment by zepumph** [comment] 2018-07-30 17:43
Yes

**Comment by zepumph** [comment] 2018-07-30 18:05
This is required for FL stable because the about dialog uses RichText and there are TextIO in the actual simulation.

**Comment by zepumph** [comment] 2018-08-14 21:32
I could see an argument in perhaps instrumenting `MultiLineText` as `RichTextIO` to potentially futureproof those usages. That would be one less potential break in the future when we convert usages of multiline text to rich text. But I see tradeoffs. That confuses us as developers when we see RichTextIO, it could be two different types. 

If we don't simplify the types, I agree with @pixelzoom that it isn't worth time in refactoring deprecated code.

**Comment by samreid** [comment] 2018-09-26 16:27
Will we be able to convert legacy versions of MultilineText to RichText, or are we constrained because of existing translations?  For example, Balloons and Static Electricity has:

```js
  "addWall": {
    "value": "Add\nWall"
  }
```

And there are 47 or so translations, like `벽\n추가`.

So there are two questions for this issue:
* Should we port everything from MultilineText to RichText?  Can we do this safely for legacy translations (will replacing `\n` with `<br>` be sufficient)?
* Should we postpone work on the IO types until we have a decision on that, or should we propose an "intermediate" solution?

These seem like dev meeting questions to me.

**Comment by pixelzoom** [comment] 2018-09-26 16:33
Reimplement MulitlineText as an extension of RichText that converts each `'\n'` to `'<br>'.  Then there's no need for MulitlineTextIO.

**Comment by pixelzoom** [comment] 2018-09-26 22:14
All of the options and methods (set/get text and fill) for MultiLineText are supported by RichText.  So MultiLineText's current implementation could presumably be replaced with:

```js
class MultiLineText extends RichText {
  constructor( text, options ) {
    super( text.replace( /\n/g, '<br>' ), options );
  }
}
```

**Comment by chrisklus** [comment] 2018-09-27 18:44
From dev meeting 9/27/18: @pixelzoom volunteers to take his suggestion in https://github.com/phetsims/scenery-phet/issues/392#issuecomment-424784116 for a test drive.

**Comment by pixelzoom** [comment] 2018-09-27 19:01
Unpublished repos that use MultiLineText, these should be converted to RichText:

- [ ] black-body-spectrum

Published repos that use MultiLineText, these should be tested after changing MultiLineText:

- [ ] balloons-and-static-electricity
- [ ] build-an-atom
- [ ] chains
- [ ] expression-exchange
- [ ] isotopes-and-atomic-mass
- [ ] joist
- [ ] least-squares-regression
- [ ] molarity
- [ ] molecules-and-light
- [ ] neuron
- [ ] states-of-matter

**Comment by pixelzoom** [comment] 2018-09-27 19:31
@samreid in brand/js/phet-io/Brand.js, we have:

```js
    additionalLicenseStatement: 'This PhET-iO interoperable simulation file requires a license.\n' +
                                'USE WITHOUT A LICENSE AGREEMENT IS STRICTLY PROHIBITED.\n' +
                                'Contact phethelp@colorado.edu regarding licensing.',
```

Since this is not a translatable string, is there any reason not to convert it to use RichText?

**Comment by samreid** [comment] 2018-09-27 19:47
RichText seems appropriate for that, thanks!

**Comment by pixelzoom** [comment] 2018-09-27 20:09
There was a tad more involved in this conversion.  In addition to the constructor, I needed to override `setText`.  And I factored out private function `replaceNewlines`, used in both the constructor and `setText`.

With the exception of states-of-matter (see https://github.com/phetsims/states-of-matter/issues/230), all sims look the same after the conversion.  Assigning to @jbphet to review, since he's also going to investigate the states-of-matter issue.

**Comment by pixelzoom** [comment] 2018-09-27 20:12
@samreid Now that MultiLineText is a subclass of RichText, I've deleted MultiLineTextIO.  Let me know if for some reason that was not appropriate.

**Comment by pixelzoom** [comment] 2018-12-29 23:01
@jbphet Can we wrap this one up?

**Comment by jbphet** [comment] 2018-12-31 18:19
Sure.  The issue with States of Matter is fixed, and the code changes for `MultiLineText` look good.  The only thing I would suggest is adding the `@depracated` annotation to `MultiLineText`.  I added it, and am assigning back to @pixelzoom in case there was some reason that the annotation wasn't used initially.

**Closed** 2019-01-01 20:52 UTC
Labels: dev:phet-io, status:ready-for-review
