### ISSUE TITLE
CT maxHeight should be null or a positive number

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/scenery-phet#538] opened 2019-10-08 15:14 UTC
```
scenery-phet : accessibility-fuzzBoard : require.js : run
Query: brand=phet&ea&fuzzBoard&a11y&memoryLimit=1000
Uncaught Error: Assertion failed: maxHeight should be null (no constraint) or a positive number
Error: Assertion failed: maxHeight should be null (no constraint) or a positive number
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1570538357335/assert/js/assert.js:22:13)
    at ContextLossFailureDialog.setMaxHeight (https://bayes.colorado.edu/continuous-testing/snapshot-1570538357335/scenery/js/nodes/Node.js?bust=1570544665033:2493:17)
    at ContextLossFailureDialog.set maxHeight [as maxHeight] (https://bayes.colorado.edu/continuous-testing/snapshot-1570538357335/scenery/js/nodes/Node.js?bust=1570544665033:2505:35)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570538357335/sun/js/Dialog.js?bust=1570544665033:270:24
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1570538357335/axon/js/Multilink.js?bust=1570544665033:41:20)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1570538357335/axon/js/TinyEmitter.js?bust=1570544665033:59:55)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1570538357335/axon/js/Property.js?bust=1570544665033:264:27)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1570538357335/axon/js/Property.js?bust=1570544665033:175:16)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1570538357335/axon/js/Property.js?bust=1570544665033:334:34)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570538357335/joist/js/Sim.js?bust=1570544665033:625:42
id: Bayes Chrome
Approximately 10/8/2019, 6:39:17 AM
```

**Comment by samreid** [comment] 2019-10-08 15:17
Duplicate of https://github.com/phetsims/joist/issues/582, closing.

**Closed by samreid** 2019-10-08 15:17 UTC
Labels: type:automated-testing
