### ISSUE TITLE
Change how we hide ariaHerald alert content

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#490] opened 2019-04-12 17:54 UTC
It was discovered in https://github.com/phetsims/ohms-law/issues/136 that the way we remove alert content from the DOM interferes with how mobile VO reads alerts.

```js
  timer.setTimeout( () => { liveElement.textContent = ''; }, 200 );
```

The purpose of this is to make it impossible to read alert content again with  the virtual cursor once it is spoken. But it will interrupt mobile VO from completing the alert. We need another way to do something similar.

I tried adding `aria-relevant="additions"` which should theoretically make it so that only additions to the `aria-live` region are announced. But it had no effect...

I discovered that replacing `liveElement.textContent = '';` with `liveElement.hidden = true` fixed the problem on  mobile VO, but it prevented alerts from working correctly with NVDA. However, setting hidden behind a timeout seems to work OK on NVDA.  Maybe this gives the a11y tree time to update, who knows.

```js

      liveElement.hidden = false;

      // after a short delay, set the textContent for the screen reader to anounce, must be done
      // asyncrounously from setting hidden above or else the screen reader will fail to read
      // the content
      timer.setTimeout( () => {
        AccessibilityUtil.setTextContent( liveElement, textContent );

        // after a short delay, hide the content so that it cant be read with the virtual cursor
        // Using `hidden` rather than setting textContent works better than clearing the textContent on mobileVO, see https://github.com/phetsims/scenery-phet/issues/490
        timer.setTimeout( () => {
          liveElement.hidden = true;
        }, 200 );
      }, 200 );
```

We should try this with
- [x] NVDA
- [x] JAWS
- [x] VO
- [x] Mobile VO

**Comment by jessegreenberg** [comment] 2019-04-12 20:01
@KatieWoe could you please test VO on MacOS with this version and make sure alerts are working OK?

https://phet-dev.colorado.edu/html/ohms-law/1.4.0-dev.32/phet/ohms-law_en_phet.html

Maybe just make sure that ~10 alerts come through.

**Comment by KatieWoe** [comment] 2019-04-12 20:13
Looks ok from my tests @jessegreenberg

**Comment by jessegreenberg** [comment] 2019-04-12 20:13
Cool, thank you @KatieWoe!

**Comment by jessegreenberg** [comment] 2019-04-15 21:48
@zepumph and I noticed today that alerts are duplicated, at least in the a11y view and I think it is because of this. My theory is that the MutationObserver of the a11y view is registering the new change as we remove alert content from the DOM.

**Comment by zepumph** [comment] 2019-04-15 23:51
@jessegreenberg, please note that in GFLB, when toggling the constant size checkbox, I get between 2 and 3 of the same alert.

**Comment by jessegreenberg** [comment] 2019-04-16 00:07
OK thanks @zepumph, I will take a look. Duplications we were seeing elswhere were fixed by the above commits which only show the alerts in the a11y view on DOM Node insertions. I am still seeing duplicate alerts for the GFLB checkboxes.

**Comment by jessegreenberg** [comment] 2019-04-16 00:19
I believe the remaining duplicates are caused by https://github.com/phetsims/gravity-force-lab-basics/issues/117, @zepumph can you please confirm? I think this can be closed again if you agree.

**Comment by terracoda** [comment] 2019-04-16 12:02
FYI, I have been experiencing duplicate alerts in the sonification wrapper for a long time. This seems to be a MacOS problem, just thought I would mention it here. I always had a suspicion it had something to do with the iframe. 

I can't seem to find a specific issue, though I thought made a least one.

**Comment by jessegreenberg** [comment] 2019-04-16 15:25
Understood @terracoda, was it this one? https://github.com/phetsims/a11y-research/issues/132

**Comment by zepumph** [comment] 2019-04-22 17:40
Review:


>      this.announcingEmitter.emit( textContent, withClear || DEFAULT_WITH_CLEAR );


- [ ] Since `DEFAULT_WITH_CLEAR` is true, then this is buggy if you pass in a `withClear` value of "false"


>      // must be done asynchronously from setting hidden above or else the screen reader
      // will fail to read the content

- [ ]  This makes sense, but why do we have to wait 200ms? Did you try only 10ms or 0ms? I worry about the delay stacking going on throughout the alerting framework. I don't want extra time to sneak in if it doesn't need to

- [ ] Expanding off of the above point. Was the inner `200` ms timeout designed as well? Does that need to be so long as well?

* updateLiveElement is very nicely commented, good job.

- [ ] Have we tested `withClear` at all? It looks like UtteranceQueue doesn't use it, and no where else does either. I wonder if we shouldn't just delete it because of its complexity? If it stick around, I'm curious why setting the text content to blank doesn't need to be async like hidden does. Maybe we can convince ourselves that the new Utterance logic developed in https://github.com/phetsims/scenery-phet/issues/485 replaces what `withClear` was originally trying to accomplish.


**In a11y view**

>            if ( mutation.addedNodes.length > 0 ) {

- [ ] Could you add a comment to this line. Even though I'm reviewing it with this issue in mind, I still don't really understand what is happening.


Let me know how I can help.

**Comment by jessegreenberg** [comment] 2019-04-23 18:09
Thanks very much for reviewing @zepumph!

> This makes sense, but why do we have to wait 200ms?

It likely comes from before we had utteranceQueue, lets try to reduce it to nearly nothing so that the timing doesn't complicate utteranceQueue.

> Maybe we can convince ourselves that the new Utterance logic developed in #485 replaces what withClear was originally trying to accomplish.

I suspect that is the case, lets try to remove it.

**Comment by jessegreenberg** [comment] 2019-04-23 22:41
@zepumph I think the above is addressed by removing optional `withClear`, reducing the timeout delays in https://github.com/phetsims/scenery-phet/issues/491, and adding the requested documentation. Would you mind taking another look at your convenience?

**Comment by zepumph** [comment] 2019-04-24 00:28
This is all very nice thanks! Closing

**Comment by zepumph** [comment] 2021-02-12 20:34
Over in https://github.com/phetsims/ratio-and-proportion/issues/348 QA and I found that setting hidden like this prevents alerts on JAWS perhaps ~75% of the time. This occurs in some of our published sims as well. Reopening.

**Comment by zepumph** [comment] 2021-02-12 20:36
When I use this patch, JAWS correctly speaks alerts, but iOS VO again gets cut off mid alert. 

```diff
Index: js/AriaHerald.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/AriaHerald.js b/js/AriaHerald.js
--- a/js/AriaHerald.js	(revision a146f5ba46cf4974ffb98b0e3cb175b416b52d34)
+++ b/js/AriaHerald.js	(date 1613162119557)
@@ -151,7 +151,7 @@
     liveElement.textContent = '';
 
     // element must be visible for alerts to be spoken
-    liveElement.hidden = false;
+    // liveElement.hidden = false;
 
     // must be done asynchronously from setting hidden above or else the screen reader
     // will fail to read the content
@@ -162,10 +162,11 @@
       // behind at least 200 ms delay or else alerts may be missed by NVDA and VoiceOver, see
       // https://github.com/phetsims/scenery-phet/issues/491
       stepTimer.setTimeout( () => {
+        liveElement.textContent = '';
 
         // Using `hidden` rather than clearing textContent works better on mobile VO,
         // see https://github.com/phetsims/scenery-phet/issues/490
-        liveElement.hidden = true;
+        // liveElement.hidden = true;
       }, 200 );
     }, 0 );
   }

```

We seem to be at some sort of impasse on how to make AriaHerald behave well for all screen readers.

**Comment by zepumph** [comment] 2021-02-12 20:53
So it looks like JAWS will say the first 4 alerts, cooresponding to the number of polite live elements we have, but once they have all been hidden, they no  longer work with JAWS.

**Comment by zepumph** [comment] 2021-02-12 20:58
This completely fixes JAWS, but doesn't work on iOS at all.
```diff

Index: js/AriaHerald.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/AriaHerald.js b/js/AriaHerald.js
--- a/js/AriaHerald.js	(revision a146f5ba46cf4974ffb98b0e3cb175b416b52d34)
+++ b/js/AriaHerald.js	(date 1613163496098)
@@ -166,6 +166,14 @@
         // Using `hidden` rather than clearing textContent works better on mobile VO,
         // see https://github.com/phetsims/scenery-phet/issues/490
         liveElement.hidden = true;
+        stepTimer.setTimeout( () => {
+          liveElement.textContent = '';
+
+          // Using `hidden` rather than clearing textContent works better on mobile VO,
+          // see https://github.com/phetsims/scenery-phet/issues/490
+          liveElement.hidden = false;
+
+        }, 200 );
       }, 200 );
     }, 0 );
   }

```

**Comment by zepumph** [comment] 2021-02-12 21:03
This patch didn't fix JAWS at all:

```Index: js/AriaHerald.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/AriaHerald.js b/js/AriaHerald.js
--- a/js/AriaHerald.js	(revision a146f5ba46cf4974ffb98b0e3cb175b416b52d34)
+++ b/js/AriaHerald.js	(date 1613163725474)
@@ -146,13 +146,13 @@
    */
   updateLiveElement( liveElement, textContent ) {
 
+    // element must be visible for alerts to be spoken
+    liveElement.hidden = false;
+
     // fully clear the old textContent so that sequential alerts with identical text will be announced, which
     // some screen readers might have prevented
     liveElement.textContent = '';
 
-    // element must be visible for alerts to be spoken
-    liveElement.hidden = false;
-
     // must be done asynchronously from setting hidden above or else the screen reader
     // will fail to read the content
     stepTimer.setTimeout( () => {

```

**Comment by zepumph** [comment] 2021-02-12 21:14
I also found that JAWS alerts were totally fixed by https://github.com/phetsims/ratio-and-proportion/issues/348#issuecomment-777907966 (removing the hiding of elements), but then you can access stale alerts at the end of the DOM (after the PDOM). This got me wondering if it is possible to hide this region in another way. `aria-disabled` didn't work.

**Comment by zepumph** [comment] 2021-02-12 21:18
I would have thought that display wouldn't effect screen reader output, but this was just as broken with JAWS, as setting hidden

```diff

Index: js/AriaHerald.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/AriaHerald.js b/js/AriaHerald.js
--- a/js/AriaHerald.js	(revision a146f5ba46cf4974ffb98b0e3cb175b416b52d34)
+++ b/js/AriaHerald.js	(date 1613164512203)
@@ -151,7 +151,7 @@
     liveElement.textContent = '';
 
     // element must be visible for alerts to be spoken
-    liveElement.hidden = false;
+    liveElement.style.display = 'block';
 
     // must be done asynchronously from setting hidden above or else the screen reader
     // will fail to read the content
@@ -165,7 +165,7 @@
 
         // Using `hidden` rather than clearing textContent works better on mobile VO,
         // see https://github.com/phetsims/scenery-phet/issues/490
-        liveElement.hidden = true;
+        liveElement.style.display = 'none';
       }, 200 );
     }, 0 );
   }

```

**Comment by zepumph** [comment] 2021-02-12 21:26
using aria-busy seems to work as a way to have the virtual cursor not be able to access the aria live elements. This was only tested in chrome, but it worked very well!

```
Index: js/AriaHerald.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/AriaHerald.js b/js/AriaHerald.js
--- a/js/AriaHerald.js	(revision a146f5ba46cf4974ffb98b0e3cb175b416b52d34)
+++ b/js/AriaHerald.js	(date 1613164729414)
@@ -151,7 +151,7 @@
     liveElement.textContent = '';
 
     // element must be visible for alerts to be spoken
-    liveElement.hidden = false;
+    liveElement.setAttribute( 'aria-busy', false );
 
     // must be done asynchronously from setting hidden above or else the screen reader
     // will fail to read the content
@@ -165,7 +165,7 @@
 
         // Using `hidden` rather than clearing textContent works better on mobile VO,
         // see https://github.com/phetsims/scenery-phet/issues/490
-        liveElement.hidden = true;
+        liveElement.setAttribute( 'aria-busy', true );
       }, 200 );
     }, 0 );
   }

```

The main issue with the above patch is that we aren't clearing the text content after setting, and so JAWS won't say an alert if it is the same as the alert content that is in the element from the last time. You can reproduce this by pressing the reset all button 5 times (because there are 4 polite elements). On the 5th time, the alert isn't spoken.

**Comment by zepumph** [comment] 2021-02-12 21:36
I also want to note that there are some similar-ish open issues in the JAWS issue tracker. Like https://github.com/FreedomScientific/VFO-standards-support/issues/296

**Comment by jessegreenberg** [comment] 2021-02-12 21:43
I just tried JAWS in Firefox and it isn't happening there. I am also seeing the bug in NVDA on Chrome now (but not Firefox). So I am thinking that it may actually be Chrome bug.

**Comment by zepumph** [comment] 2021-02-12 22:07
@jessegreenberg and I were able to confirm that this issue seems to be with all alerting done on Chrome (JAWS and NVDA).

@jessegreenberg and I figured out a platform specific solution that works on everything we have tested thus far. It also notest that setting `hidden` is more of a workaround for VO anyways, and that it shouldn't be standard. 

We will make sure that QA hits this hard in the next RC for Ration and Proportion. We will also do extensive testing on all platforms first.

**Comment by jessegreenberg** [comment] 2021-02-12 22:21
If this works well, we probably want to redeploy all other sims with interactive-descriptions in a batch maintenance release. But we wanted to check in with @emily-phet first since this will take development and QA time. I would guess it will take 2-3 hours to go through the batch maintenance release process, and I would think about an hour of QA time to spot check the dozen or so sims that would be redeployed.

@emily-phet can you confirm that this is OK?

**Comment by emily-phet** [comment] 2021-02-13 14:12
Yes, please go ahead with the maintenance release.

**Comment by terracoda** [comment] 2021-02-15 13:58
Awesome! I am so happy for maintenance releases on these sims, in particular BASE and Friction as they both now have accessible grab and drag on mobile. Not sure if that automatically gets included, but it would be great if it did (no pressure).

Just an FYI, I did notice an issue with BASE last week - the charges were not displaying properly in the wall. See issue https://github.com/phetsims/balloons-and-static-electricity/issues/481

**Comment by jessegreenberg** [comment] 2021-02-15 16:35
OK thanks! A maintenance release for an unrelated issue is currently in progress, when that is done I will start this one (probably Wed 2/17).

@terracoda unfortunately this batch maintenance release won't include mobile accessibility or other improvements. Including mobile accessibility would be a much more destabilizing change and isn't something I would be comfortable doing in a batch of maintenance releases. This maintenance release will only apply the verified fix to each sim. But that also means that it is very unlikely for each sim to pick up new bugs in master, such as the one you pointed out in https://github.com/phetsims/balloons-and-static-electricity/issues/481.

**Comment by terracoda** [comment] 2021-02-15 16:38
Ok, gotcha, @jessegreenberg! BASE will get a good maintenance release when the sound design is done. I'll have to be patient.

**Comment by zepumph** [comment] 2021-02-18 01:52
https://github.com/phetsims/ratio-and-proportion/issues/348 has been tested and closed, so I think our patch worked.

I created https://github.com/phetsims/scenery-phet/issues/671 to do a batch MR to support alerts. I think this issue is ready to close. Please reopen if you feel differently.

**Closed** 2021-02-18 01:52 UTC
Labels: dev:a11y
