### ISSUE TITLE
Consider consolidating color constants

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/scenery-phet#221] opened 2016-02-29 21:31 UTC
There are 5 copies equivalent to the following in scenery-phet:

``` js
      // Default base code matches the yellow in the PhET logo (the one with the paper airplane).
      baseColor: new Color( 242, 233, 22 )
```

and now one copy of the color in making-tens.

Ideally we should have colors pinned to specific things related to our logo factored out?

**Comment by pixelzoom** [comment] 2016-11-16 00:04
Duplicate of https://github.com/phetsims/scenery-phet/issues/270, addressed, closing.

**Closed by pixelzoom** 2016-11-16 00:04 UTC
