### ISSUE TITLE
"Timing" is incorrect term in TimingControlsKeyboardHelpSection.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#882] opened 2024-10-20 18:09 UTC
Related to https://github.com/phetsims/scenery-phet/issues/881 ...

TimingControlsKeyboardHelpSection should be renamed to TimeControlsKeyboardHelpSection, and the string changed from "Timing" to "Time".

**Comment by marlitas** [comment] 2024-11-05 17:31
Closing as a duplicate of https://github.com/phetsims/scenery-phet/issues/881

**Closed by marlitas** 2024-11-05 17:31 UTC
Labels: design:description
