### ISSUE TITLE
generalize ResetAllButton

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#230] opened 2016-04-13 14:48 UTC
In MOTHA, a reset button is needed for the spectrometer, and something that looks like ResetAllButton (but with a different color scheme) is a natural fit.  But there are problems with using ResetAllButton for something other than "reset all":

(1) It should have been named ResetButton, so it could be used for resetting other things. 

(2) It contains some accessibility stuff that also seems to assume that it's only use to reset "all".

(3) The baseColor can be changed, but the arrow color currently cannot.

To address, I propose to factor:
• factor out ResetButton
• make ResetAllButton extend ResetButton, adding the "all"ness
• add options.arrowColor

**Comment by pixelzoom** [comment] 2016-04-13 15:36
Should also rename `ResetAllShape` to `ResetShape`.

**Comment by pixelzoom** [comment] 2016-04-13 16:07
Work completed.  To summarize what was done:

• factored out a general ResetButton
• ResetAllButton extends ResetButton, adding things specific to 'rest all'
• ResetAllShape renamed to ResetShape
• ResetAllButton.RESET_ALL_BUTTON_BASE_COLOR moved to PhetColorScheme

Assigning to @jbphet to review, since he was the primary author of ResetAllButton.  Reviewing this is high priority because extensive changes were required and ResetAllButton is core.

After @jbphet reviews, this should be assigned to someone (@jessegreenberg?) to review the accessibility aspects of ResetAllButton, since I have no idea how to test that.

**Comment by jbphet** [comment] 2016-04-13 17:23
General plan sounds reasonable, changes look good, and I regression tested the reset all button in a handful of simulations.  I also tested changing the base color of the button and the color of the arrow, and it all worked fine.  Assigning to @jessegreenberg to review the accessibility aspects.

**Comment by jessegreenberg** [comment] 2016-04-18 23:14
Accessible content looks good, I removed the accessibleDescription from options since it is not being used.  Tested with NVDA and JAWS screen readers, it is working well.  Reassigning to @pixelzoom in case there is anything left to do for this issue.

**Closed** 2016-04-18 23:38 UTC
Labels: priority:2-high, status:ready-for-review
