### ISSUE TITLE
Artifact on play/pause button

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#581] opened 2020-03-04 23:29 UTC
In dev meeting agenda for 3/5/2020, @jbphet said:

> Artifact on play/pause button - any idea where it came from and/or who should get the issue?

Do you mean `PlayPauseButton`?  I can't reproduce. Please provide an example.

**Comment by jbphet** [comment] 2020-03-04 23:46
From SOM, this is the version on master as displayed in Chrome on my main, high resolution display.  Note the light portion on the lower right where the shadow should end.

![image](https://user-images.githubusercontent.com/3082831/75933025-229a3d80-5e36-11ea-9c28-33fac0a40af7.png)

This is from the same version of the sim as seen on my low-rez auxiliary monitor.  The light portion on the lower right is even more noticeable.

![image](https://user-images.githubusercontent.com/3082831/75933439-401bd700-5e37-11ea-8f19-be18dae0f8ac.png)

Here are the same two clips but from the published version:

![image](https://user-images.githubusercontent.com/3082831/75933067-3cd41b80-5e36-11ea-8607-0d78d9ba9063.png)

![image](https://user-images.githubusercontent.com/3082831/75933528-72c5cf80-5e37-11ea-8d19-45ce80927b81.png)

**Comment by pixelzoom** [comment] 2020-03-05 19:34
3/5/20 dev meeting:
@jessegreenberg volunteered to look at this, since he recently added `scaleFactorWhenPaused.`

**Comment by jessegreenberg** [comment] 2020-03-09 18:07
I am seeing this in rutherford-scattering 1.0.0 from 08/2016.

![image](https://user-images.githubusercontent.com/6396244/76243392-a1182600-620e-11ea-9c71-b2ade10cf358.png)

But I confirmed that I am not seeing this in states-of-matter 1.1.0 from 10/2018.

**Comment by jessegreenberg** [comment] 2020-03-09 18:19
I am not seeing this on the PlayPauseButton in https://phet-dev.colorado.edu/html/states-of-matter/1.2.0-dev.1/phet/states-of-matter_en_phet.html (01/2020) in states-of-matter. But I am seeing it on the ResetAllButton in that same version.

![image](https://user-images.githubusercontent.com/6396244/76244691-f1908300-6210-11ea-80eb-5748f5cadbf3.png)

**Comment by jessegreenberg** [comment] 2020-03-09 21:37
After digging further I have determined that the shading on master is actually how it has always been by default. What we are seeing is just the default stroke around the button. The reason that the buttons in SOM used to look different is because they had a custom black stroke that could not be seen on the black background of that sim. This stroke was removed in https://github.com/phetsims/states-of-matter/issues/246. But by default, the stroke for 3D buttons is a darker version of the button base color. This is why all RestAllButtons don't have the shadow going right to the edge of the button. It is also why StepButton in published SOM has similar shading:
![image](https://user-images.githubusercontent.com/6396244/76259302-b780aa80-622b-11ea-91b9-b4b5ce2c465b.png)

From this comment, it seems that default stroke was very intentional
```js
  else if ( typeof ( options.stroke ) === 'undefined' ) {
    // No stroke was defined, but it wasn't set to null, so default to a stroke based on the base color of the
    // button.  This behavior is a bit unconventional for Scenery nodes, but it makes the buttons look much better.
    enabledStroke = baseDarker4;
    disabledStroke = disabledBaseDarker4;
  }
```
And there is a default lineWidth of 0.5.

I don't think anything more needs to be done for this issue, @jbphet what do you think?

**Comment by jbphet** [comment] 2020-03-10 15:30
Sounds good, thanks for the investigation @jessegreenberg.  I think I'll improve the look in States of Matter and leave it at that.

**Comment by jbphet** [comment] 2020-04-22 20:11
I tried setting the custom stroke for the play-pause button, the step button, and the reset-all button and it looked better when running normally, but worse in projector mode.  I then tried using the color profile to switch the strokes, but this didn't look very good in projector mode either.  I'm going to bail on this an leave it as is, since the amount of time I'm spending on it doesn't seem to be worth the marginal benefit.  Closing.

**Closed by jbphet** 2020-04-22 20:11 UTC
