### ISSUE TITLE
problems with FaucetNode "tap" feature

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/scenery-phet#593] opened 2020-03-30 22:34 UTC
@pixelzoom EDIT:  This issue was originally reported in ph-scale, during dev testing.  It was determined to be a general problem in SCENERY_PHET/FaucetNode, so this issue was transferred to scenery-phet repo.

---

**Test Device**

MacBook Air

**Operating System**

macOS 10.15.2

**Browser**

Google Chrome 80.0.3987.149

**Problem Description**

For https://github.com/phetsims/QA/issues/487. If you click the faucet valve (click and don’t hold) it fills the beaker with 0.05 L every time except for the first time you do it. The first time you do it, it fills the beaker with 0.06 L. Happens in 1.4.0-dev.15, published, and published pH Scale: Basics.

There is no issue with emptying the beaker in a similar fashion. It's just filling that has the issue.

**Visuals**

![issue](https://user-images.githubusercontent.com/31285590/77968107-bb8c6f00-72a3-11ea-92ab-3fa9d71afe16.gif)

<details>
<summary><b>Troubleshooting Information</b></summary>
!!!!! DO NOT EDIT !!!!!
Name: ‪pH Scale‬
URL: https://phet-dev.colorado.edu/html/ph-scale/1.4.0-dev.15/phet/ph-scale_all_phet.html
Version: 1.4.0-dev.15 2020-03-23 21:08:00 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
Language: en-US
Window: 1440x821
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment] 2020-03-31 17:33
I've transferred this issue to scenery-phet.  And I've created https://github.com/phetsims/ph-scale/issues/157 (deferred) for tracking in ph-scale.

Assigning to @ariel-phet to prioritize and assign this issue.

**Comment by ariel-phet** [comment] 2020-04-08 01:53
@lmulhall-phet @arouinfar @pixelzoom 

@lmulhall-phet certainly a nice find an attention to detail!

I am actually going to go ahead and close this issue:

1. The "tap" feature was intended to do teach the user that the faucet plunger could be used to dispense liquid. In early interviews, we saw people tapping on this control point, nothing happening and getting confused. So the amount dispensed is not really important, it is more to show that the faucet plunger allows dispensing.

2. I do not necessarily recall why we put in `tapToDispenseAmount` - but I don't think the user necessarily has an expectation that a consistent amount will always be dispensed. This UI component does not imply the precision of a tweaker button.

3. The majority of users will figure out that the faucet can be used as designed (as seen in user testing), so doubtful the will continue to tap unless trying to make a fine adjustment. 

4. Considering the age of this sim, and no user complaints suggestions along this line of thought, I just see it as a non issue.

We can reopen this issue (or a new one) if a complain/suggestion appears from users or a client.

**Closed by ariel-phet** 2020-04-08 01:53 UTC
Labels: type:bug
