### ISSUE TITLE
GridNode API suggestions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#601] opened 2020-04-23 16:27 UTC
@zepumph mentioned that @jessegreenberg had created a new component, `GridNode`.  Since I've been using a lot of grids in math sims, I took a look.   Overall very nice, and I'd like to use this in the future (or maybe retrofit existing sims).

A few suggestions:

* Doc says: 
> The grid has "minor" lines and optionally "major" lines which are generally more prevalent.

This is backwards. Minor lines are always more prevalent than major lines. Minor spacing is further division of major spacing.  This is why they are called major and minor. For example, major lines spaced 50 unit apart, minor lines spaced 10 units apart.  Major lines are also typically required, while minor lines are optional.

* Add verification that major spacing is > minor spacing.  

* Add verification that minor spacing also must be a multiple of major spacing.

* Rename `minorPath` and `majorPath` to `minorLines` and `majorLines` respectively.  When this is instrumented for PhET-iO, I can almost guarantee that designers will want to be able to control visibility of major vs minor lines, and see the Nodes presented as "lines", not "paths". 
 
* If you don't do the previous rename... `minorLineOptions` and `majorLineOptions`  are propagated to `minorPath` and `majorPath` respectively.  Use either "Line" or "Path" consistently. 

* Add PhET-iO instrumentation.  Shouldn't we be doing this for any new UI component?

**Comment by jessegreenberg** [comment] 2020-04-23 19:10
> This is backwards. Minor lines are always more prevalent than major lines.

I used the wrong word, it should be "prominent" rather than "prevalent", ill change to 
"The grid has "minor" lines and optionally "major" lines which are generally more visually prominent."

>  Major lines are also typically required, while minor lines are optional.

All lines are optional for this GridNode, do you think this would be a better constructor?
```js
  constructor( gridWidth, gridHeight, options ) {
    options = merge( {
      majorHorizontalLineSpacing: null,
      majorVerticalLineSpacing: null,
      minorHorizontalLineSpacing: null,
      minorVerticalLineSpacing: null
```

**Comment by pixelzoom** [comment] 2020-04-23 19:18
> All lines are optional for this GridNode, do you think this would be a better constructor?

Hmm... The doc indicates that minor lines are required, and they are required constructor parameters.   So if both major and minor lines are optional, what you've proposed is a better API.  You'll presumably need an assertion that at least one type of line is specified.

**Comment by jessegreenberg** [comment] 2020-04-24 16:50
OK, all lines are now optional and I updated documentation.
> You'll presumably need an assertion that at least one type of line is specified.

I tried this, but both usages so far (EnergySkateParkGridNode and ProportionGridNode) calculate spacing for the grid after it has been constructed. This seems reasonable to me and requiring spacing on construction is inconvenient.

> Rename minorPath and majorPath to minorLines and majorLines respectively. 

Done.

> Add verification that major spacing is > minor spacing.
> Add verification that minor spacing also must be a multiple of major spacing.

GridNode spacing is mutable so this is too strict. For instance, we need to allow this sequence:
```js
gridNode.setMinorHorizontalSpacing( 5 );
gridNode.setMajorHorizontalSpacing( 10 );

// 7 is not a multiple of 10, this transient state should be OK
gridNode.setMinorHorizontalSpacing( 7 );
gridNode.setMajorHorizontalSpacing( 14 );
```

> Add PhET-iO instrumentation. Shouldn't we be doing this for any new UI component?

Yes! Will do.

**Comment by pixelzoom** [comment] 2020-04-24 19:50
I don't think that the needs of 2 sims (EnergySkateParkGridNode and ProportionGridNode) should necessarily be driving the API for a common-code component.  And not handling validation because it's "inconvenient" is a red flag for me.  Validation could be addressed by adding methods that set major and minor spacing at the same time, e.g. `setHorizontalSpacing( majorSpacing, minorSpacing )` and `setVerticalSpacing( majorSpacing, minorSpacing )`.    But I don't have time to devote to this, so I'll assign back to @jessegreenberg and @zepumph to decide if anything else should be done, and if the changes here should be part of the review that @zepumph does in #580.

**Comment by jessegreenberg** [comment] 2020-04-24 23:54
> Add verification that major spacing is > minor spacing.
> Add verification that minor spacing also must be a multiple of major spacing.
> assertion that at least one type of line is specified.

To support all three I collapsed the spacing setters into one function `setLineSpacings` so that we know the intended spacings whenever they are going to be changed.

Assigning back to @zepumph from request in https://github.com/phetsims/scenery-phet/issues/601#issuecomment-619209606, as part of review in #580.

**Comment by zepumph** [comment] 2020-04-27 18:39
>You'll presumably need an assertion that at least one type of line is specified.

Over in https://github.com/phetsims/ratio-and-proportion/issues/5 it was very helpful to be able to clear all the lines out of the GridNode given certain states (i.e. radioButton control for none/horizontal/both). Instead of needing another channel (Node.visible) to show no lines, I feel like allowing `setLineSpacings` to be passed all nulls feels flexible, simple and explicit. After talking with @jessegreenberg, I think it is best to remove the assertion ensuring that something is drawn.

>To support all three I collapsed the spacing setters into one function setLineSpacings so that we know the intended spacings whenever they are going to be changed.

This is really nice! I like this implementation more than individual functions. And it seems to solve the sim-specific constraint in https://github.com/phetsims/scenery-phet/issues/601#issuecomment-619126745

> And not handling validation because it's "inconvenient" is a red flag for me

I also like the work that was done to validate the passed in spacing parameters. I updated the logic a bit to simplify it and added more type validation that I felt made it feel more common-code like. I totally agree with you, and I also feel like it is ideal if this common code `GridNode` can meet all the griddy needs of the project. I'm happy that we can add support for clearing lines as part of the API, making this more flexible for all use cases we have and may encounter in the future.

@jessegreenberg please review the above commits, and I will see you over in https://github.com/phetsims/scenery-phet/issues/580

**Comment by brandonLi8** [comment] 2020-05-24 03:47
@zepumph @jessegreenberg This looks really nice and I'm about to port it over to 'Collision Lab' But I was thinking about it: how would a client use `GridNode` for a simulation like `Vector Addition`

![image](https://user-images.githubusercontent.com/42391580/82745136-fb208600-9d3d-11ea-9d79-f4fd00a32c7b.png)


where the major gridlines don't start at the first minor gridline? It seems to me that `GridNode` makes an assumption that grid-lines start at x=0, y=0.

One thing that could happen in `collision-lab` is that there is a zoom-in and zoom-out button, which I would need to re-adjust the grid. How would a client use `GridNode` with minor lines that also don't start at 0?

**Comment by pixelzoom** [comment] 2020-05-24 13:34
Good point @brandonLi8.  

This seems like a significant limitation.  I wouldn't be able to use GridNode in Natural Selection (NS) either, for the same reason.  There are no minor grid lines in NS, but the grid needs to scroll, for example see screenshot below.   I suspect that same would be true of griddle components like ScrollingChartNode.

<img width="1188" alt="screenshot_330" src="https://user-images.githubusercontent.com/3046552/82755451-c4279000-9d90-11ea-96a5-7e174f632c56.png">

**Comment by pixelzoom** [comment] 2020-05-24 13:37
Good point @brandonLi8.  

This seems like a significant limitation.  I wouldn't be able to use GridNode in Natural Selection (NS) either, for the same reason.  There are no minor grid lines in NS, but the grid needs to scroll, for example see screenshot below.   This is also a problem for griddle components, like XYPlotNode and ScrollingChartNode, see screenshots below from griddle demo.

<img width="1188" alt="screenshot_330" src="https://user-images.githubusercontent.com/3046552/82755451-c4279000-9d90-11ea-96a5-7e174f632c56.png">

<img width="312" alt="screenshot_331" src="https://user-images.githubusercontent.com/3046552/82755534-62b3f100-9d91-11ea-9de2-cedd959ac36a.png">
<img width="581" alt="screenshot_332" src="https://user-images.githubusercontent.com/3046552/82755536-65aee180-9d91-11ea-9ac9-8e88940f0e65.png">

**Comment by pixelzoom** [comment] 2020-05-24 13:51
I would also say that GridNode should definitely be usable in griddle.  Was that considered in the design of GridNode?  An excellent way to proceed would be to actually use GridNode in griddle, for example for the grid in XYPlot.

**Comment by jessegreenberg** [comment] 2020-05-27 20:18
Thanks @brandonLi8, I added options and setters for `verticalLineOffset` and `horizontalLineOffset` to support this. Each are applied to their respective major and minor lines. These can also be used to support scrolling, demonstrated in the scenery-phet demo. Does this fully support your use case?

>  would also say that GridNode should definitely be usable in griddle.

Thats a really good idea, Ill move GridNode to griddle.

**Comment by pixelzoom** [comment] 2020-05-27 20:35
@jessegreenberg Instead of more options, another way to determine where the grid lines should be placed would be to use a model-view transform.   Then you would specify origin, major grid lines, minor grid lines, etc. in model coordinates. That would be more consistent with graph, where we typically already have a model-view transform for plotting data.

**Comment by jessegreenberg** [comment] 2020-05-27 20:50
I can see having GridNode spacings/offsets in model coordinates and using a model-view transform but I don't see how that would get rid of options. Can you explain or show an example usage of GridNode if it were done this way?

**Comment by jessegreenberg** [comment] 2020-05-27 22:33
After https://github.com/phetsims/griddle/issues/52, GridNode uses model coordinates with an optional ModelViewTransform2.

**Comment by brandonLi8** [comment] 2020-05-27 23:36
@jessegreenberg looks good. 

Would it be too much to ask for a modelViewTransform in a property? Because there are a lot of sims where the modelViewTransform is changing (like in `Vector Addition` and in `Collision Lab`. I guess one way you could go about it is to create a new GridNode every time the modelViewTransformProperty changes, but it could be nice to have this built in. @jessegreenberg thoughts?

**Comment by jessegreenberg** [comment] 2020-05-28 16:32
Thanks @brandonLi8, you should be able to modify the GridNode without creating a new one. The previous way to do this would have been to use `setLineSpacings` to draw lines at your desired zoom level. Now grid width and height are in model coordinates as well, so if you change the model-view transform it will make your grid taller or wider as well.

I considered changing the API to have width/height in view coordinates and line spacings/offsets in model coordinates, but that would be confusing. I considered having a separate NumberProperty for zoom, but that is confusing in combination with the ModelViewTransform.

I am going to go back to having GridNode use view coordinates.

**Comment by jessegreenberg** [comment] 2020-05-28 16:43
I reverted https://github.com/phetsims/griddle/issues/52, back to @brandonLi8 for review.

**Comment by brandonLi8** [comment] 2020-05-28 17:38
Thanks @jessegreenberg. `GridNode` is good for me to use in `collision-lab`. Thanks!

**Comment by brandonLi8** [comment] 2020-05-29 21:27
@jessegreenberg I went to go to use `GridNode` in `collision-lab`. However, I'm getting 


`Uncaught Error: Assertion failed: minor spacing should be a multiple of major spacing` when I shouldn't be.

Debugging and logging my spacing (which are computed numbers), I have my major spacing as `76.5` and my minor spacing as  `15.3`, which is exactly a fifth. `76.5 % 15.3` gets me `15.299999999999997`.

**Comment by pixelzoom** [comment] 2020-06-02 16:30
> I can see having GridNode spacings/offsets in model coordinates and using a model-view transform but I don't see how that would get rid of options. Can you explain or show an example usage of GridNode if it were done this way?

See GRAPHING_LINES/GraphNode.GridNode (inner class).

**Comment by brandonLi8** [comment] 2020-06-12 18:30
It looks like @jessegreenberg switched to using a modelViewTransformProperty option in https://github.com/phetsims/griddle/issues/46. I was wondering why the Momenta Diagram grid didn't look right.

I attempted to switch to using this new option (as the offsets were also deprecated). For some reason, the horizontal lines were not rendering in.
![image](https://user-images.githubusercontent.com/42391580/84534845-e9306400-aca7-11ea-8792-ba0dd2a8df3b.png)


I confirmed (through console.log) that my horizontal spacing was being correctly passed in. I referred to the example, and noticed that it uses `ModelVIewTransform.createRectangleMapping`, when collision lab uses `ModelViewTransform2.createRectangleInvertedYMapping( bounds, gridViewBounds );` I tried switching to `ModelVIewTransform.createRectangleMapping` in collision lab (not committed) and it worked, but my vectors were flipped as expected, so I bailed.

@jessegreenberg  can you investigate this? Code for collision lab is in `collision-lab/MomentaDiagramAccordionBox`.

**Comment by jessegreenberg** [comment] 2020-06-12 18:36
Sorry @brandonLi8, I thought I inspected usages but looks like I missed this - Ill take a look.

**Comment by jessegreenberg** [comment] 2020-06-12 20:45
@brandonLi8 and I confirmed that https://github.com/phetsims/scenery-phet/issues/601#issuecomment-643424250 is no longer an issue in master.

Indeed, GridNode now uses a modelViewTransform, which will also handle
```js
      verticalLineOffset: 0,
      horizontalLineOffset: 0,
```

so I am going to remove those options.

**Comment by jessegreenberg** [comment] 2020-06-12 21:38
Commit https://github.com/phetsims/griddle/commit/7ae5d5aef3233d0b1ea4cdf65efa79ca9fe188d8 is for the comment @brandonLi8 made in https://github.com/phetsims/scenery-phet/issues/601#issuecomment-636199847.

Closing again, since changes are complete for the recommendations in https://github.com/phetsims/scenery-phet/issues/601#issuecomment-634924832 and https://github.com/phetsims/scenery-phet/issues/601#issuecomment-636199847, and it seems this is being used successfully in collision-lab (and other places).

**Closed by jessegreenberg** 2020-06-12 21:38 UTC
Labels: dev:code-review, status:ready-for-review
